
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: horizon
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs
spec:
  selector:
    component: backend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/horizon-c09/backend:latest
          imagePullPolicy: "Always"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3000
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: backend-pv-volume
              mountPath: /tmp/uploads
      volumes:
        - name: backend-pv-volume
          persistentVolumeClaim:
            claimName: backend-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horizon
      tier: frontend
  template:
    metadata:
      labels:
        app: horizon
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/horizon-c09/frontend:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80