# multistage build https://blog.logrocket.com/containerized-development-nestjs-docker/
FROM node:14.17.0-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --include=dev

COPY . .
COPY .env.production .env

RUN npm run build

FROM node:14.17.0-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --only=production

COPY . .
COPY .env.production .env
COPY --from=development /usr/src/app/dist ./dist

EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]
