
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: horizon
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: horizon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: northamerica-northeast2-docker.pkg.dev/horizon-c09/horizon-front-repo/frontend:v1
        ports:
        - containerPort: 80